### ISSUE TITLE
Any interest in external redirects?

### ISSUE THREAD

**Issue by Duder-onomy** [thoov/ember-redirect#21]
I have forked and messed with this lib to support external redirects, something like:

```
const Router = EmberRouter.extend({
  redirects: {
    jobs: 'https://some-external-job-listing-site.com',
  },
});
```
It basically bypases this libs [beforeModel](https://github.com/thoov/ember-redirect/blob/master/addon/utils/reopen-route.js#L25) if the route resembles a url. 

Any interest in this moving upstream?

**Comment by thoov** [comment]
@Duder-onomy Yes that would be a great PR!

**Comment by Duder-onomy** [comment]
Rad. I will send that PR shortly.
